// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQgN_nNzgcXwDtiaqBZdFzdO9rftFr4nY',
    appId: '1:465816958541:web:102decc0f1b5d2c3ccce04',
    messagingSenderId: '465816958541',
    projectId: 'mynotes-flutter-demoon',
    authDomain: 'mynotes-flutter-demoon.firebaseapp.com',
    storageBucket: 'mynotes-flutter-demoon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZyumKHbSqgTocd_OhZitOH7ujbFEig0',
    appId: '1:465816958541:android:7e8db45c402b7682ccce04',
    messagingSenderId: '465816958541',
    projectId: 'mynotes-flutter-demoon',
    storageBucket: 'mynotes-flutter-demoon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANFuNhL6A6ULFw-VMHAOfXbon97V6jQQc',
    appId: '1:465816958541:ios:a1c85c8cd147f14bccce04',
    messagingSenderId: '465816958541',
    projectId: 'mynotes-flutter-demoon',
    storageBucket: 'mynotes-flutter-demoon.appspot.com',
    iosBundleId: 'flutter.learn.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANFuNhL6A6ULFw-VMHAOfXbon97V6jQQc',
    appId: '1:465816958541:ios:a1c85c8cd147f14bccce04',
    messagingSenderId: '465816958541',
    projectId: 'mynotes-flutter-demoon',
    storageBucket: 'mynotes-flutter-demoon.appspot.com',
    iosBundleId: 'flutter.learn.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQgN_nNzgcXwDtiaqBZdFzdO9rftFr4nY',
    appId: '1:465816958541:web:c6fc44d898c05c40ccce04',
    messagingSenderId: '465816958541',
    projectId: 'mynotes-flutter-demoon',
    authDomain: 'mynotes-flutter-demoon.firebaseapp.com',
    storageBucket: 'mynotes-flutter-demoon.appspot.com',
  );
}
